config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }
  root to: 'static#index'

  get 'home', to: 'static#index'
  get 'about', to: 'static#about'
  get 'search/restaurants', to: 'search#restaurants'
  get 'search/google-places', to: 'search#google_places'
  get 'sitemap', to: 'static#sitemap'
  get 'privacy-policy', to: 'static#privacy_policy'
  get 'terms', to: 'static#terms'
  get 'top-users/berries', to: 'top_users#berries'

  resources :restaurants do
    member do
      get :report
      get :comments
    end
  end

  resources :users do
    member do
      get :notifications
      get :name
    end
  end

  resources :contacts, only: [:new, :create]

  resources :comments, only: [:edit, :update, :destroy] do
    member do
      get :report
    end
  end

  resources :notifications, only: [:destroy]

  resources :report_comments, only: [:create]
  resources :report_items, only: [:create]
  resources :report_restaurants, only: [:create]

  resources :item_comments, only: [:new, :create]
  resources :item_photos, only: [:new, :show, :create, :destroy]
  resources :restaurant_comments, only: [:new, :create]
  resources :reply_comments, only: [:new, :create]

  resources :favorites, only: [:create, :destroy]
  resources :content_berries, only: [:create, :destroy]

  resources :items do
    member do
      get :report
      get :item_ingredients
    end

    member do
      get :comments
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, inverse_of: :favorites
  belongs_to :restaurant, inverse_of: :favorites
  belongs_to :item, inverse_of: :favorites
  belongs_to :profile, :class_name => 'User', :foreign_key  => "profile_id"

  scope :restaurants, -> { joins(:restaurant) }
  scope :items, -> { joins(:item) }
  scope :profiles, -> { joins(:user) }

  validates :user_id, presence: true
  validates :restaurant_id, uniqueness: { allow_blank: true, scope: :user_id } if :restaurant
  validates :item_id, uniqueness: { allow_blank: true, scope: :user_id } if :item
  validates :profile_id, uniqueness: { allow_blank: true, scope: :user_id } if :profile

  def type
    [:restaurant, :item, :profile].each do |type|
      return type if send(type)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @model = Favorite.new(favorite_params)
    @model.user = current_user

    load_resource
    load_view_options

    @model.save ? successfull_create : unsuccessfull_create
  end

  def destroy
    #right now if there is no model, it will just fail. after load model.  Should include a custom js script to render a new form, because clearly is must have already been deleted or no existant.  Make sure the user does not already have duplicate resource favorite.
    load_model
    load_resource
    load_view_options

    return unless validate_user_permission(@model.user)

    @model.destroy ? successfull_destroy : unsuccessfull_destroy
  end

  private

  def favorite_params
    params.require(:favorite).permit(:restaurant_id, :item_id, :profile_id)
  end

  def successfull_create
    flash.now[:success] = "You have added the #{@resource_class_name} to your favorites."

    respond_to do |format|
      format.html { copy_flash;
      redirect_to restaurant_url(@model.restaurant), status: :created }

      format.js { render 'create', status: :created }
    end
  end

  def unsuccessfull_create
    flash.now[:error] = "Unable to add the #{@resource_class_name} to your favorite list"

    respond_to do |format|
      format.html { redirect_to restaurant_url(@model.restaurant), status: :unprocessable_entity }

      format.js { render 'errors', status: :unprocessable_entity }
    end
  end

  def successfull_destroy
    flash.now[:notice] = "Successfully removed the #{@resource_class_name} from your favorites."

    @model = Favorite.new(@model.type => @resource)

    respond_to do |format|
      format.html { copy_flash;
      #this has to be dynamically determined
      redirect_to restaurant_url(@model.restaurant) }

      format.js
    end

  end

  def unsuccessfull_destroy
    flash.now[:error] = "Unable to remove the #{@resource_class_name} from your favorites."

    # these redirects will have to get changed dynamically to the @favorites_type
    respond_to do |format|
      format.html { render redirect_to( restaurant_url(@model.restaurant)), status: :unprocessable_entity }

      format.js { render 'errors', status: :unprocessable_entity }
    end
  end

  def load_model
    return unsuccessful_destroy unless (@model = Favorite.find(params[:id]))
  end

  def load_resource
    @resource_id = @model.send("#{@model.type}_id")
    @resource_name = @model.type
    @resource_class_name = @model.send(@model.type).class.name.downcase.to_sym
  end

  def copy_flash
    flash[:success] = flash.now[:success] if flash.now[:success]
    flash[:error] = flash.now[:error] if flash.now[:error]
  end
end

app/views/favorites/_new.html.haml
= form_for(favorite_resource, remote: true, url: favorites_path(header: local_assigns[:header]), html: {id: "new_favorite_#{resource}_#{resource_id}", class: 'hidden'}) do |f|
  = f.hidden_field "#{resource}_id".to_sym, value: resource_id
  = f.submit '#', class: 'hidden'
%a{ href: 'javascript:void(0)', class: 'submit', onclick: 'submitForm(this)'}
  %span.ui.icon.header.icon-option
    %i.star.icon.popup{"data-content" => 'Add to Favorites'}
    = 'Favorite' if local_assigns[:header]

app/views/favorites/_remove.html.haml
= form_for favorite_resource, method: :delete, remote: true, url: favorite_path(favorite_resource, header: local_assigns[:header]), html: {id: "remove_favorite_#{resource}_#{resource_id}", class: 'hidden'} do |f|
  = f.submit '#', class: 'hidden'
%a{ href: 'javascript:void(0)', class: 'submit', onclick: 'submitForm(this)'}
  %span.ui.icon.header.icon-option
    %i.star.icon.remove.popup{"data-content" => "Remove from Favorites"}
    = 'Un-favorite' if local_assigns[:header]

app/views/favorites/create.js.haml
:plain
  var content = ("#{ escape_javascript render('favorites/remove', favorite_resource: @model, resource: @resource_name, resource_id: @resource_id, header: @header)}");
  var messages = ("#{ escape_javascript render('layouts/messages')}");
  var form = $("#new_favorite_#{@resource_name}_#{@resource_id}")
  var favorite = form.closest('.favorite')

  favorite.html(content)
  initializeAjaxForm(form)

  var animationArea = favorite.find('.ui.icon.header');

  handleSuccess(animationArea, messages)
  initializePopup();

app/views/favorites/destroy.js.haml
:plain
  var content = ("#{ escape_javascript render('favorites/new', favorite_resource: @model, resource: @resource_name, resource_id: @resource_id, header: @header)}");
  var messages = ("#{ escape_javascript render('layouts/messages')}");
  var form = $("#remove_favorite_#{@resource_name}_#{@resource_id}")
  var favorite = form.closest('.favorite')

  favorite.html(content)
  initializeAjaxForm(form)

  var animationArea = favorite.find('.ui.icon.header');

  handleSuccess(animationArea, messages)
  initializePopup();

app/views/favorites/errors.js.haml
:plain
  var form = $("form[id$='#{@resource_name}_#{@resource_id}']")
  var favorite = form.closest('.favorite')
  var animationArea = favorite.find('.ui.icon.header');
  var messages = ("#{ escape_javascript render('layouts/messages')}");

  handleSuccess(animationArea, messages)