config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }
  root to: 'static#index'

  get 'home', to: 'static#index'
  get 'about', to: 'static#about'
  get 'search/restaurants', to: 'search#restaurants'
  get 'search/google-places', to: 'search#google_places'
  get 'sitemap', to: 'static#sitemap'
  get 'privacy-policy', to: 'static#privacy_policy'
  get 'terms', to: 'static#terms'
  get 'top-users/berries', to: 'top_users#berries'

  resources :restaurants do
    member do
      get :report
      get :comments
    end
  end

  resources :users do
    member do
      get :notifications
      get :name
    end
  end

  resources :contacts, only: [:new, :create]

  resources :comments, only: [:edit, :update, :destroy] do
    member do
      get :report
    end
  end

  resources :notifications, only: [:destroy]

  resources :report_comments, only: [:create]
  resources :report_items, only: [:create]
  resources :report_restaurants, only: [:create]

  resources :item_comments, only: [:new, :create]
  resources :item_photos, only: [:new, :show, :create, :destroy]
  resources :restaurant_comments, only: [:new, :create]
  resources :reply_comments, only: [:new, :create]

  resources :favorites, only: [:create, :destroy]
  resources :content_berries, only: [:create, :destroy]

  resources :items do
    member do
      get :report
      get :item_ingredients
    end

    member do
      get :comments
    end
  end
end

app/views/shared/_add_restaurant_blurb.html.haml
.row
  .ui.container.center.add-blurb
    Do you know a restaurant that has vegan options?
    %br
    = link_to 'Add it today!', new_restaurant_path()

app/views/shared/_authentication_wrapper.html.haml
= render 'shared/header', title: @app_name
.ui.container
  .ui.middle.aligned.center.aligned.grid.page-content
    .row
      .sixteen.wide.mobile.fourteen.wide.tablet.column.authentication-form
        = yield

app/views/shared/_edit_toggle.html.haml
- klass ||= 'ui header toggle'
- remote = true if remote.nil?
= link_to path, remote: remote, class: klass do
  %i.write.icon.popup{"data-content" => data_content}

app/views/shared/_form_wrapper.html.haml
- klass = klass || 'custom-form'
%div{class:  "sixteen wide mobile fourteen wide tablet column #{klass}"}
  = form_for resource, html: { class: 'ui form large' } do |f|
    - if title ||= nil
      .ui.form-title
        %h3.ui.header
          = title
    - if messages?
      = render 'shared/form_errors'
    = yield f

app/views/shared/_header.html.haml
- image ||= nil
- additional_header_content ||= nil
- additional_header_options ||= nil
- editable ||= nil
.ui.center.aligned.page-header
  %h1.ui.header{class: (editable ? 'inline-icon' : '')}
    = title
    - if editable
      %span.edit-item.bottom.aligned
        = render 'shared/edit_toggle', path: send("edit_#{@model.class.name.underscore.downcase}_path", @model), klass: 'ui header', data_content: 'Edit', remote: false
  - if location?
    .location
      = display_location
    -if phone?
      .phone
        = link_to "tel: #{@model.location.phone_number}" do
          %i.call.icon
          = @model.location.phone_number
  - if image
    = render'shared/header_photo', image: image, editable: editable
  - if defined?(subtitle)
    %h2.sub.header
      = subtitle
  = render 'shared/added_by'
  = render 'restaurants/business_hours'
  - if additional_header_content
    .row.options
      -if additional_header_options
        = render additional_header_content, additional_header_options
      - else
        = render additional_header_content
- if show_messages? && (messages = find_messages).present?
  %span.flash-messages
    = render 'layouts/messages', list: true, messages: messages

app/views/shared/_header_photo.html.haml
- if image == 'gallery'
  = render('shared/photo_gallery')
- else
  .restaurant-img
    = display_header_img(image, editable)
  - if @model.try(:persisted?) && current_page?(item_path(@model))
    .gallery.title
      = link_to new_item_photo_path(item_id: @model.id), remote: true, class: 'toggle' do
        %i.photo.icon.popup{"data-content" => "Add new Photo"}
        Add Photo

app/views/shared/_list_header.html.haml
.ui.grid.middle.aligned.list-header
  - if list_title = options[:list_title]
    .sixteen.wide.column.center.list-title
      - if options[:multiple_lists]
        = options[:multiple_lists]
      - else
        %h2.ui.divided.header
          = list_title
      - if options[:sub_title]
        - if options[:restaurant].vegan_menu
          %p
            This Restaurant Provides a<br>
            %span.highlight
              *Vegan/Vegetarian Menu*
            - if options[:restaurant].menu_url.present?
              <br>
              = link_to 'View Menu', format_url(options[:restaurant].menu_url)
        - else
          %p.sub.header.warning
            %span.highlight*Warning*
            \- The following is merely a guide.  Nothing displayed is 100% certified vegan unless specified.  Please always confirm with restaurant employees.
  .sixteen.wide.mobile.column
    - if row_title = options[:row_title]
      %h2.ui.divided.header
        = row_title
    - if options[:sortable]
      = render 'shared/sort_form'
    - if list_options = options[:list_options]
      %span.list-options.right.floated
        = render list_options

app/views/shared/_message.html.haml
%div{class: "#{flash_class(type)}"}
	= value

app/views/shared/_messages.html.haml
.ui.messages
  %div{class: "#{flash_class(type)} close"}
    %i.close.icon
    - messages.each do |attr, messages|
      - if messages.present?
        %ul
          - messages.each do |msg|
            %li
              = "#{attr.to_s.titleize} #{msg}"

app/views/shared/_modal_image.html.haml
%div.center.aligned
  .ui.image.full-photo
    = image_tag(uploaded_path(@model.photo))
  %div.user-row
    = image_tag(uploaded_path(@model.user.avatar, :thumb), class: 'ui avatar image')
    %span
      = link_to @model.user.name, @model.user

app/views/shared/_navigation_items.html.haml
= link_to 'Home', root_path, class: "item"
= link_to 'Restaurants', restaurants_path, class: 'item'
= link_to 'Users', users_path, class: 'item'
= link_to 'About', about_path, class: 'item'
= link_to 'Contact Us', new_contact_path, class: 'item footer-only'
-# - if current_user
-#   %span.ui.dropdown.item
-#     = current_user.name || 'User Options'
-#     %i.dropdown.icon
-#     .menu
-#       = link_to user_path(current_user), class: 'item' do
-#         %i.user.blue.icon
-#         Profile
-#       = link_to edit_user_path(current_user), class: 'item' do
-#         %i.write.blue.icon
-#         Edit Profile
-#       = link_to destroy_user_session_path, method: :delete, class: 'item' do
-#         %i.sign.out.blue.icon
-#         Sign Out
-# - else
-#   = link_to 'Sign Up', new_user_registration_path, class: 'item'
-#   = link_to 'Log In', new_user_session_path, class: 'item'

app/views/shared/_new_comment_form.html.haml
= form_for(model, html: { class: 'ui form large center' }) do |f|
  = f.fields_for :comment do |ff|
    = render 'shared/comment_fields', object: ff
  = f.hidden_field hidden_id
  = f.submit 'Create Comment', class: 'ui circular button blue'

app/views/shared/_sort_form.html.haml
.ui.dropdown.item.sort
  %h2.ui.header
    Sort
    %i.dropdown.icon
  .menu
    = restaurant_sort_options

app/views/shared/_users_list.html.haml
.ui.grid.container.page-content
  .row
    .two.wide.computer.only.column
    .sixteen.wide.mobile.twelve.wide.computer.column
      .ui.relaxed.divided.list.restaurant-list
        %h2.ui.divided.header
          Something
          -# - if current_page?('/search/restaurants')
          -#   Most Relevent
          -# - else
            -# = option_view_name(@sort_by)
        -# = render 'shared/sort_form' unless current_page?('/search/restaurants')
        - users.each do |user|
          %a.item{:href => "#{user_path(user)}"}
            .content
              .ui.grid.middle.aligned
                .eight.wide.mobile.column
                  %h3.ui.header
                    -# = image_tag(image_path(user), height: '60', width:'60', class: 'ui image middle aligned')
                    = user.name || 'No Username'
                .eight.wide.mobile.column.right.aligned.item-count
                  %h4
                    %span.highlight
                      = user.berry_count
                    %strong
                      Berries
      -# .ui.container.center.aligned.new-content
      -#   = will_paginate users, renderer: WillPaginateSemanticUi::ActionView::Renderer