config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }
  root to: 'static#index'

  get 'home', to: 'static#index'
  get 'about', to: 'static#about'
  get 'search/restaurants', to: 'search#restaurants'
  get 'search/google-places', to: 'search#google_places'
  get 'sitemap', to: 'static#sitemap'
  get 'privacy-policy', to: 'static#privacy_policy'
  get 'terms', to: 'static#terms'
  get 'top-users/berries', to: 'top_users#berries'

  resources :restaurants do
    member do
      get :report
      get :comments
    end
  end

  resources :users do
    member do
      get :notifications
      get :name
    end
  end

  resources :contacts, only: [:new, :create]

  resources :comments, only: [:edit, :update, :destroy] do
    member do
      get :report
    end
  end

  resources :notifications, only: [:destroy]

  resources :report_comments, only: [:create]
  resources :report_items, only: [:create]
  resources :report_restaurants, only: [:create]

  resources :item_comments, only: [:new, :create]
  resources :item_photos, only: [:new, :show, :create, :destroy]
  resources :restaurant_comments, only: [:new, :create]
  resources :reply_comments, only: [:new, :create]

  resources :favorites, only: [:create, :destroy]
  resources :content_berries, only: [:create, :destroy]

  resources :items do
    member do
      get :report
      get :item_ingredients
    end

    member do
      get :comments
    end
  end
end

app/models/content_berry.rb
class ContentBerry < ApplicationRecord
  include NotificationResource

  belongs_to :user, inverse_of: :content_berries
  belongs_to :restaurant, inverse_of: :content_berries
  belongs_to :item, inverse_of: :content_berries
  belongs_to :comment, inverse_of: :content_berries

  after_create :notifiy_content_creator
  after_destroy :remove_notifications

  scope :restaurants, -> { joins(:restaurant) }
  scope :items, -> { joins(:item) }
  scope :comments, -> { joins(:restaurant) }

  def for_user
    send(self.type).user
  end

  def type
    [:restaurant, :item, :comment].each do |type|
      return type if send(type)
    end
  end

  private
  # TODO: I HAVE TO PREVENT FROM PEOPLE clicking the berry button too many times
  # I dont want there to be a notification for every time someone double
  # clicks on the berry button
  def notifiy_content_creator
    return unless (creator = content_creator) && creator != self.user

    notify_user(creator)
  end

  def content_creator
    send(self.type).try(:user)
  end
end

app/controllers/content_berries_controller.rb
class ContentBerriesController < ApplicationController
  before_action :authenticate_user!

  def create
    @model = ContentBerry.new(content_berries_params)
    @model.user = current_user
    load_view_options

    load_resource

    @model.save ? successfull_create : unsuccessfull_create
  end

  def destroy
    load_model
    load_resource
    load_view_options

    return unless validate_user_permission(@model.user)

    @model.destroy ? successfull_destroy : unsuccessfull_destroy
  end

  private

  def content_berries_params
    params.require(:content_berry).permit(:comment_id, :restaurant_id, :item_id)
  end

  def successfull_create
    flash.now[:success] = "Successfully gave a berry to the user."

    respond_to do |format|
      format.html { copy_flash;
      #this has to be dynamically determined
      redirect_to restaurant_url(@model.restaurant), status: :created }

      format.js { render 'create', status: :created }
    end
  end

  def unsuccessfull_create
    flash.now[:error] = "Unable to give a berry to the user."

    respond_to do |format|
      format.html { redirect_to restaurant_url(@model.restaurant), status: :unprocessable_entity }

      format.js { render 'errors', status: :unprocessable_entity }
    end
  end

  def successfull_destroy
    flash.now[:notice] = "Took the berry away from the user."

    @model = ContentBerry.new(@model.type => @resource)

    respond_to do |format|
      format.html { copy_flash;
      #this has to be dynamically determined
      redirect_to restaurant_url(@model.restaurant) }

      format.js
    end

  end

  def unsuccessful_destroy
    flash.now[:error] = "Unable to take away a berry from the user."

    # these redirects will have to get changed dynamically to the @favorites_type
    respond_to do |format|
      format.html { render redirect_to( restaurant_url(@model.restaurant)), status: :unprocessable_entity }

      format.js { render 'errors', status: :unprocessable_entity }
    end
  end

  def load_model
    return unsuccessful_destroy unless (@model = ContentBerry.find(params[:id]))
  end

  def load_resource
    @resource_id = @model.send("#{@model.type}_id")
    @resource_name = @model.type
    @resource_class_name = @model.send(@model.type).class.name.downcase.to_sym
  end

  def copy_flash
    flash[:success] = flash.now[:success] if flash.now[:success]
    flash[:error] = flash.now[:error] if flash.now[:error]
  end
end

app/views/content_berries/_new.html.haml
= form_for(content_berry, remote: true, url: content_berries_path(header: local_assigns[:header]), html: {id: "new_#{resource_name}_berry_#{resource_id}", class: 'hidden'}) do |f|
  = f.hidden_field "#{resource_name}_id".to_sym, value: resource_id
  = f.submit '#', class: 'hidden'
%a{ href: 'javascript:void(0)', class: 'submit', onclick: 'submitForm(this)'}
  %span.ui.icon.header.icon-option
    %span.icon.popup{"data-content" => "Give Berry"}
      = image_tag('default/berry-green.svg')
    = 'Give Berry' if local_assigns[:header]

app/views/content_berries/_remove.html.haml
= form_for content_berry, method: :delete, remote: true, url: content_berry_path(content_berry, header: local_assigns[:header]), html: {id: "remove_#{resource_name}_berry_#{resource_id}", class: 'hidden'} do |f|
  = f.submit '#', class: 'hidden'
%a{ href: 'javascript:void(0)', class: 'submit', onclick: 'submitForm(this)'}
  %strong.ui.icon.header.icon-option
    %span.icon.popup{"data-content" => "Remove Berry"}
      = image_tag('default/berry-purple.svg')
    = 'Remove' if local_assigns[:header]

app/views/content_berries/_toggle.html.haml
%span.berry
  - if (current_user && (berry = current_user.content_berries.find_by(resource => model)))
    = render 'content_berries/remove', content_berry: berry, resource_name: resource, resource_id: model.id, header: local_assigns[:header]
  - else
    = render 'content_berries/new', content_berry: ContentBerry.new(), resource_name: resource, resource_id: model.id, header: local_assigns[:header]

app/views/content_berries/create.js.haml
:plain
  var content = ("#{ escape_javascript render('content_berries/remove', content_berry: @model, resource_name: @resource_name, resource_id: @resource_id, header: @header)}");
  var messages = ("#{ escape_javascript render('layouts/messages')}");
  var form = $("#new_#{@resource_name}_berry_#{@resource_id}")
  var berry = form.closest('.berry')

  berry.html(content)
  initializeAjaxForm(form)

  var animationArea = berry.find('.ui.icon.header');
  handleSuccess(animationArea, messages)
  initializePopup();

app/views/content_berries/destroy.js.haml
:plain
  var content = ("#{ escape_javascript render('content_berries/new', content_berry: @model, resource_name: @resource_name, resource_id: @resource_id, header: @header)}");
  var messages = ("#{ escape_javascript render('layouts/messages')}");
  var form = $("#remove_#{@resource_name}_berry_#{@resource_id}")
  var berry = form.closest('.berry')

  berry.html(content)
  initializeAjaxForm(form)

  var animationArea = berry.find('.ui.icon.header');

  handleSuccess(animationArea, messages)
  initializePopup();

app/views/content_berries/errors.js.haml
:plain
  var form = $("form[id$='#{@resource_name}_berry_#{@resource_id}']")
  var messages = ("#{ escape_javascript render('layouts/messages')}");
  var berry = form.closest('.berry')
  var animationArea = berry.find('.ui.icon.header');

  handleSuccess(animationArea, messages)